freebsd_instance:
  image: freebsd-12-1-release-amd64

task:
  env:
    AUTOMATED_TESTING: 1
    MAKEFLAGS: -j4

  cpan_cache:
    folder: perl_modules
    reupload_on_changes: true # set to false if there is a fingerprint script
    #fingerprint_script:
    #  - echo $CIRRUS_OS
    #  #- perl -v
    #  - echo 2020056

  install_script:
    - sudo pkg install -y autoconf automake libtool pkgconf sqlite3 gmake
    - sudo pkg install -y p5-App-cpanminus
    - cpanm --local-lib=~/perl_modules local::lib && eval $(perl -I ~/perl_modules/lib/perl5/ -Mlocal::lib)
    - cpanm --installdeps --notest Alien::proj
    - cpanm -v Alien::proj
    - cpanm -v Alien::libtiff
    - cpanm -v Alien::geos::af
    - cpanm --installdeps --notest Alien::gdal
    - cpanm --notest Alien::gdal
    - cpanm --installdeps --notest Geo::GDAL::FFI
    - cpanm Geo::GDAL::FFI
    - cpanm --notest Task::Biodiverse::NoGUI

  script:
    - prove -l
