language: perl
matrix:
    include:
        - perl: '5.30'
        - perl: '5.28'
          env: LANG="de_DE"
        - perl: '5.26'
        - perl: '5.24'
          env: BD_TEST_GUI=1
        - perl: '5.22'


distro: trusty
sudo: required
cache:
  directories:
    - perl_modules

before_install:

  #  local::lib target is cached
  - cpanm --notest local::lib
  - eval "$(perl -Mlocal::lib=${PWD}/perl_modules)"
  - cpanm --notest List::MoreUtils~0.425
  - cpanm --notest Sort::Key::Natural
  - cpanm --notest Geo::ShapeFile@3.00
  - cpanm --notest Browser::Start
  #  get the latest Geo::GDAL::FFI,
  #  and make sure something happens at the command prompt
  #  so we avoid timeouts when building Alien::gdal
  - cpanm -v --notest Geo::GDAL::FFI | perl -ne 'BEGIN {$|=1; open our $log, ">", "build.log"}; print "\n" if 0 == ($. % 90); print "."; print {$log} $_;' || cat build.log

  #  Disable Gtk stuff for speed reasons
  #  Reinstate when we add the GUI variant
  - if [ $BD_TEST_GUI ]; then sudo apt-get install libgnomecanvas2-dev; fi;

  # Here as well as cpanfile because of dependency problems if not installed before Gnome2::Canvas
  - if [ $BD_TEST_GUI ]; then cpanm --notest ExtUtils::Depends ExtUtils::PkgConfig Glib Gtk2; fi;

  - if [ $BD_TEST_GUI ]; then cpanm --quiet --installdeps --notest --with-all-features .; fi;


script: prove -l -j4
# blocklist
branches:
  except:
  - ppm
  - /appveyor/
