branches:
  except:
    - /travis/
skip_tags: true

cache:
  - C:\Strawberry

install:
  - if not exist "C:\strawberry" appveyor-retry choco install strawberryperl --version 5.28.1.1
  #- appveyor-retry choco upgrade strawberryperl --version 5.28.1.1
  - set ST=C:\Strawberry
  - set PATH=%ST%\perl\bin;%ST%\perl\site\bin;%ST%\c\bin;%PATH%
  - cd C:\projects\%APPVEYOR_PROJECT_NAME%
  
  #  aliens should be cached now
  - cpanm --quiet --notest Module::Compile
  - ppm set repository BDV_PPM http://biodiverse.unsw.edu.au/downloads/ppm
  #- ppm verify --upgrade Alien-geos-af Alien-proj Alien-freexl Alien-sqlite Alien-spatialite
  #- ppm verify --upgrade Alien-MSYS
  #- ppm install Alien-geos-af Alien-proj Alien-freexl Alien-sqlite Alien-spatialite
  #- ppm install Alien-MSYS
  - cpanm --notest Alien::geos::af Alien::proj Alien::freexl
  - cpanm --notest Alien::sqlite
  - cpanm --notest Alien::spatialite
  #- set MAKEFLAGS="-j 2"
  #- cpanm --notest --installdeps PDL
  #- cpanm --notest --installdeps Alien::gdal
  - ppm install http://biodiverse.unsw.edu.au/downloads/ppm/PDL.ppd
  - ppm install Alien-gdal
  ##  make sure something goes to screen for Alien::gdal to avoid timeouts
  ##- cpanm -v https://github.com/shawnlaffan/perl-alien-gdal.git
  - cpanm --notest Geo::GDAL::FFI
  - cpanm --notest -v Sereal
  - cpanm --notest Task::Biodiverse::NoGUI
  - cpanm --notest List::MoreUtils~0.425
  - cpanm --notest List::Unique::DeterministicOrder
  - cpanm --notest Sort::Key::Natural
  ##- cpanm --installdeps --notest --with-all-features .


build_script:
  - set BD_NO_TEST_GUI=1
  #- prove -l
  - perl -e "1"

