branches:
  except:
    - /travis/
skip_tags: true

cache:
  #- C:\Strawberry

install:
  #- if not exist "C:\strawberry" appveyor-retry choco install strawberryperl --version 5.30.2.1
  - appveyor-retry choco upgrade strawberryperl --version 5.28.1.1
  - set ST=C:\Strawberry
  - set PATH=%ST%\perl\bin;%ST%\perl\site\bin;%ST%\c\bin;%PATH%
  - cd C:\projects\%APPVEYOR_PROJECT_NAME%
  
  #  aliens should be cached now
  - cpanm --quiet --notest Module::Compile
  
  #  need a more recent version for Alien::gdal
  
  - cpanm --quiet --notest Alien::Build
  ##  make sure something goes to screen for aliens to avoid timeouts
  - cpanm -v --notest Alien::geos::af Alien::proj 
  - cpanm -v --notest Alien::sqlite
  #- cpanm -v --notest Alien::freexl
  #- cpanm -v --notest Alien::spatialite
  - cpanm -v Alien::gdal
  - ppm set repository BDV_PPM http://biodiverse.unsw.edu.au/downloads/ppm
  - ppm install --location http://biodiverse.unsw.edu.au/downloads/ppm PDL
  - cpanm --notest Geo::GDAL::FFI
  - cpanm --notest Sereal
  - cpanm --notest Task::Biodiverse::NoGUI
  - cpanm --notest List::MoreUtils~0.425
  - cpanm --notest List::Unique::DeterministicOrder
  - cpanm --notest Sort::Key::Natural
  - cpanm --notest Win32::LongPath
  - cpanm --notest Geo::ShapeFile@3.00
  - cpanm --notest Browser::Start
  #- cpanm --verbose Data::Recursive
  ##- cpanm --installdeps --notest --with-all-features .


build_script:
  - prove -l
  #- perl -e "1"

