branches:
  except:
    - /travis/
skip_tags: true

cache:
  - C:\strawberry

install:
  - if not exist "C:\strawberry" choco install strawberryperl --version 5.24.1.1
  - set ST=C:\strawberry
  - set PATH=%ST%\perl\bin;%ST%\perl\site\bin;%ST%\c\bin;%PATH%
  - cd C:\projects\%APPVEYOR_PROJECT_NAME%
  
  #  aliens should be cached now
  - cpanm -v Alien::geos::af
  - cpanm -v Alien::gdal
  #  make sure something goes to screen for Alien::gdal to avoid timeouts
  #- cpanm -v https://github.com/shawnlaffan/perl-alien-gdal.git
  - cpanm Geo::GDAL::FFI 
  - cpanm --notest Task::Biodiverse::NoGUI
  - cpanm --notest List::MoreUtils~0.425
  - cpanm --notest List::Unique::DeterministicOrder
  - cpanm --notest Sort::Key::Natural
  #- cpanm --installdeps --notest --with-all-features .


build_script:
  - set BD_NO_TEST_GUI=1
  - prove -l

